name: Build openchokin/front Docker Image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ImageBuild:
    name: Build openchokin/front Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Slack notification of build start
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: GitHub Actions
          SLACK_COLOR: "#4381de"
          SLACK_ICON: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          SLACK_TITLE: Start openchokin/front image build
          SLACK_MESSAGE: |
            Run number : #${{ github.run_number }}

      - name: Check out
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: walnuts1018
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          version: latest

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node_modules
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        uses: actions/cache@v3
        with:
          path: "front/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('front/package-lock.json') }}

      - name: install
        working-directory: ./front
        run: npm install

      - name: build
        working-directory: ./front
        run: npm run build

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/walnuts1018/openchokin/front:latest
            ghcr.io/walnuts1018/openchokin/front:${{ github.sha }}-${{ github.run_number }}

  SucceessNotification:
    if: ${{ success() }}
    name: Send Success Message
    needs: [ImageBuild]
    runs-on: ubuntu-latest
    steps:
      - name: Send Message to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: GitHub Actions
          SLACK_ICON: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          SLACK_TITLE: openchokin/front image build succeeded
          SLACK_MESSAGE: |
            openchokin/front image build succeeded
            Image: openchokin/front
            Run number : #${{ github.run_number }}

  FailureAlert:
    if: ${{ failure() }}
    name: Notify failure
    needs: [ImageBuild]
    runs-on: ubuntu-latest
    steps:
      - name: Send Failure Alert to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: GitHub Actions
          SLACK_ICON: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          SLACK_TITLE: openchokin/front image build failed
          SLACK_COLOR: danger
          SLACK_MESSAGE: |
            openchokin/front image build failed
            Image: openchokin/front
            Run number : #${{ github.run_number }}
