name: Build Test
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install
        working-directory: ./front
        run: npm install
      - name: build
        working-directory: ./front
        run: npm run build
